name: get-version
on:
  push:
    branches:
      - main

jobs:
  get-variable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - run: Write-Output "${{ steps.tagName.outputs.tag }}"
